### ISSUE TITLE
Add a good introduction and reference documentation

### ISSUE THREAD

**Issue by andrew-johnson-4** [andrew-johnson-4/InPlace#10]
Examples examples examples

**Comment by Richard5656** [comment]
Is this legal? If so what would it output?

```
A<b,C<d>> = A<Int,C<Bool>>;
R<C<d>>
--Output--
?????
```

**Comment by andrew-johnson-4** [comment]
There is a command line implementation which I think works ok on Linux. Hopefully other platforms too, though I haven't tested.

In test.rl

```
A<b,C<d>> = A<Int,C<Bool>>;
R<C<d>>
```

running `relog test.rl` outputs

```
R<C<Bool>>
```

which I can confirm is expected.

**Comment by Richard5656** [comment]
Ill try to get this CLI running on my WSL. I got a new laptop a couple months ago and I don't have much installed because I've been busy because of school.

**Comment by Richard5656** [comment]
I got a non CLI version running after installing rust and cargo on my Ubuntu WSL. I'm going to try nesting to see how far I can get this to go. This is a really open ended language there's not much too it. It's just replacing the inside with predefined stuff. From the left and right.  It's really fun to play with. I wonder if I can do basic recursion with this. Granted there'd be no base case.

**Comment by Richard5656** [comment]
this is a big hypothetical. But could I use this for grammar definitions for programming languages? Like a sort of ebnf?

**Comment by Richard5656** [comment]
```expr<stk_ptr,term,expr_op> := 
term<stk_ptr,Int,term_op>

//example of adding to the stack Reverse polish notation calucluator

<expr 
            <stk_ptr, 
                         term<stk_ptr ,12, nothing>,+>
>
```

**Comment by Richard5656** [comment]
```
nothing = nothing;

expr<stk_ptr,term,expr_op> := R<Ptr,Term,op>;
term<stk_ptr,Int, term_op> : = R<Ptr,Int,op>;

Int = expr | Int;

if <expr,block,else> := R<expr,block, else>;

else<if,block>;


if<expr<stk_ptr,12,expr<stk_ptr, 13,nothing>,"<">, 
            block<Stuff inside block>,
noelse>
```
It's a very rough way i've done on testing grammar's. I'm sure there's a better way. I just remembered that uppercase letters meant constant. Not sure if that really changes anything. I'm probably using this tool in ways it was never meant to be used.

**Comment by andrew-johnson-4** [comment]
The biggest problem that I think you'll run into is that recursion is not allowed more than once. This could be enabled with a flag if you want to use Relog to program, at which point the language would be Turing Complete.

Would you be interested in using Relog as if it were Prolog?

**Comment by andrew-johnson-4** [comment]
Recursion can now be enabled with a flag:

```
relog --recurse tests/123.rl
```

So Relog is a real programming language now I guess.

**Comment by andrew-johnson-4** [comment]
Those are some interesting use cases that you are trying. Definitely not what I was thinking of when I started this project, but we can try to support that now.

**Comment by Richard5656** [comment]
I barely know any Prolog. I read through one tutorial 2 years ago and never used it. I'm not even sure if I know how to use it. I should probably learn Prolog first and use it for a while. I think I'm misusing Relog. With my uses of it. I'm assuming you want to show type hierarchy like within Haskell where it's Num with Float and Int being under the Num class.

**Comment by andrew-johnson-4** [comment]
The Relog unification is loosely based on Prolog. They are very similar.

**Comment by Richard5656** [comment]
Yeah it felt like defining prolog facts but never any rules. I'm still unsure of the direction you want to take Relog. I'm just giving suggestions on what I think of Relog. I thought it was originally supposed to be a rules checker?

**Comment by andrew-johnson-4** [comment]
It is for types, but it is trivial to permit recursion. So I just added it in case anyone wants to write real code with it.

**Comment by andrew-johnson-4** [comment]
I looked up rules/queries from Prolog and I think it is possible to create that interaction with Bind in Relog, however it would be nice to have a simpler interface for it. That would be good to implement Rules from LM, but that would also require the concept of precedence which is tricky.

**Comment by andrew-johnson-4** [comment]
The [basics of Prolog](http://www.cs.trincoll.edu/%7Eram/cpsc352/notes/prolog/factsrules.html) rules are already working if there were and/or/not primitives which could be added in the standard library:

```relog
Friends<X,Y> := And<Likes(X,Y),Likes(Y,X)>            /* X and Y are friends if they like each other */
Hates<X,Y> := Not<Likes<X,Y>>                            /* X hates Y if X does not like Y. */
Enemies<X,Y> := And<Not<Likes<X,Y>>,Not<Likes<Y,X>>>
```

**Comment by andrew-johnson-4** [comment]
My idea for adding another interaction was related to [LM Rules](https://github.com/andrew-johnson-4/-?tab=readme-ov-file#syntax-and-formatting) which are cross-cutting rules that override direct rules when applicable and desirable.

**Comment by Richard5656** [comment]
I dumped your previous comment through google bard and I think I understand. You want privatives for Relog to make it more like Prolog. But you want there to be some precedence so those rules don't get overwritten by user defined facts. 

I had a problem with this once in my own version of Forth. 

Forth has these operations called words. '+' is a word primative. To define a word a user could do this : word_name 1 + ;

: + 1 - ; ( I just overwrote the primative + )

I think this is where you're going?

**Comment by andrew-johnson-4** [comment]
Relog was an attempt to be as close to as powerful as Prolog while still being strongly normalizing. While we're at it we might make some other improvements too. LM depends on this tricky feature where the programs choose _shortcuts_ during evaluation based on some goal. I want to build LM on top of PunC/Relog so that feature needs to be implemented somewhere in here.

**Comment by Richard5656** [comment]
Is it like instead of lazy evaluation you have a guided evaluation for these shortcuts? Guided evaluation being taking the best path weather it'd be the fastest or the least memory intensive?

**Comment by andrew-johnson-4** [comment]
The optimization goal that I had in mind was for code optimization and alternative forms. The actual output of the program would be different for these shortcuts, but they would have been defined as an equivalent form, so technically OK.

**Comment by Richard5656** [comment]
Ah I got it. So since there is no state you think that it'd be easier to make an alternative path to the end goal. It's basically saying if I already have this result then why not find a shorter path aka the shortcut to get me there faster or better.

The heap and stack example was throwing me off, but I think I see the picture. 

Is there any previous implementations of such a feature though? I would assume it'd be like executing your program in a stack machine before optimizing the redundant or unused parts out. Since it's strongly normalizing  you wouldn't have an infinite amount of possibilities so you'd end up with a finite amount. All you would need to do is test each path.

**Comment by andrew-johnson-4** [comment]
I want the compiler to level up and be a little smarter. Everything is working towards that goal.

**Comment by Richard5656** [comment]
I've studied a little bit of compiler theory and I've never heard of such teqnique. But it is feasible for pure functional programing. But what about necessary side effects, How will side effects be handled? 

I should probably check out LM and LSTS. I'm not a huge academic for programing language design.

**Comment by andrew-johnson-4** [comment]
I am planning on handling side effects in Relog. Each side effect gets a nominal type that hopefully doesn't depend so much on evaluation order:

```
CreateFile<build_artifact_location,build_artifact_contents>
```

**Comment by Richard5656** [comment]
Ok so that makes the side effects more predictable. 

You write a lot of Functional programming languages. 
I'm having a hard time understanding them. I'm just going to fire off some questions I have.

So do they compile down to PubC? 

Also what exactly are these type proofs for? Are they to make sure that values of certain types should be interacting?

Is Relog a modular type system?

What is the problem all this aims to solve or goal? Is it only shortcuts?

On paper shortcuts work have you tested them out yet?

I have family over for Christmas so I'll be occupied for a couple hours.

**Comment by andrew-johnson-4** [comment]
I just moved PunC/Relog to a 1.0 release this year. This is all very new to me too. The idea for the PunC type system is novel I think, and yes everything goes down the drain toward that. PunC in a narrow sense is no different than Simply Typed Lambda Calculus, so it is a very conservative choice for targeting as an intermediate form. The actual final output might compile past that, but there are a million platforms. PunC is the IR for all my projects.

Types are annotations for Terms. They carry extra information to help make choices and verification steps.

Relog is certainly modular I think. It is a simple nominal type system that attempts to complement the PunC term system.

LSTS is the first project that I started a little over two years ago. I have learned a lot since then, and started 3 new projects to break out some functionality into independent standalone projects. PunC is the rock bottom. Relog is a type system. LM is a compiler backend. LSTS is a compiler frontend.

Shortcuts are new to me, though they leverage Big Step Semantics which are a common compiler strategy.

Merry Christmas!

**Comment by Richard5656** [comment]
I started my programing language design a little bit before 2 years ago too.
PunC looks pretty cool. I'm looking to make a stack based machine to be my main IR. But I cannot seem to  focus on a singular design. Everytime I redesign I recompile my version of C, Tenshi C. I have I think 1 of my 8 bit stack machienes on github. But there are loads of countless other ones where I design them and never end up implementing them or never uploading them. My main goal is to really understand compiler theory. A lot of the time I end up having to write my own compilers because I'm using a custom instruction set that I designed or I'm programing in an environment where the compiler provided by GCC gets annoying to use. Compiler optimizations done by GCC are great but sometimes it abstracts away much needed assembly which I would like. Having to continuously write volatile is driving me insane. Sometimes a compiler with no optimizations is better for understanding some systems. A lot of the compilers I write are hand crafted with no external libraries. I don't use alot of AST's or IR in general because I'm still working that out on what my stack machine should look like. Trying to get a standard going so I can make my own LLVM.

 I mainly want to understand compiler design and theory. I want to be able to design a custom language. Preferably low level. I have curiosity towards functional and logic paradigms but not enough too look deep into how they are made or how they work in the hood. I know that functional languages like Haskell compile down to typed lambda calculus. I know the basic rules of lambda calculus. It's just functional languages are very esoteric to me. Technically I program in somewhat functional languages like Forth and Lisp which uses function composition. But these are closer to Turing Machines rather than functional machines. I took interest into your projects because it was something different than what I was used to. It's similar to what I usually do, compiler(possible intermediate representation) -> assembler -> Custom ISA. You have it for functional programing LSTS -> LM -> Relog/PunC. I just find that pretty neat.


Only complaint I have is there isn't a lot of documentation on how this all works. Or there is and I'm not finding it. I genuinely would like to know more.

I haven't read the dragon book but I did read https://compilers.iecc.com/crenshaw/
